export const SET_SEARCH_FIELD = "SET_SEARCH_FIELD";
export const REQUST_ROBOTS_PENDING = "REQUST_ROBOTS_PENDING";
export const REQUST_REBOTS_SUCCES = "REQUST_REBOTS_SUCCES";
export const REQUST_REBOTS_FAILED = "REQUST_REBOTS_FAILED";
